name: deploy

env:
  AZURE_WEBAPP_NAME: directoryBrowser    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'src/DirBrowser/DirBrowser7'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.x'           # set this to the dot net version to use

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.13.0
    - name: build react
      run: |
        cd src
        cd DirBrowser
        cd dir_react_browser
        npm i  --force 
        npm run build
        cp -r build/* ../DirBrowser7/wwwroot/    

    - name: build help
      run: |
        cd src
        cd DirBrowser
        cd help
        npm i
        npm run build
        rm ../DirBrowser7/wwwroot/help/default.html
        cp -r build/* ../DirBrowser7/wwwroot/help/    

    - name: prepare plugins
      run: |
        cd src
        cd DirBrowser
        dotnet restore
        dotnet tool restore
        echo 'build plugins'
        dotnet r buildPlugins

    - name: dotnet build
      run: |
        cd src
        cd DirBrowser
        dotnet build -c Debug

    - name: dotnet publish artifacts
      run: |
        cd src
        cd DirBrowser        
        dotnet build -c Debug
        #dotnet publish -r win-x64 -c Debug -o myappArtifact  --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=true
        dotnet r publishFull
        #dir myappArtifact 

  
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: DirBrowser7_Win64
        path: 'src/DirBrowser/myappArtifact'

    - name: Archive Release  
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'releaseWinX64.zip'
        path: '${{github.workspace}}/src/DirBrowser/myappArtifact/*'
        directory: '${{github.workspace}}/'
        exclusions: '*.git* /*node_modules/* .editorconfig'       

    - name: Release
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        body: "Latest Release for Manual Install"
        generate_release_notes: true
        draft: false
        prerelease: false
        files:  |
            ${{github.workspace}}/releaseWinX64.zip
        #tag: v${{ env.GITHUB_SHA }}
        tag_name: vDirBrowser${{ github.run_id }}
        

    - name: delete older-releases@v0
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        #repo: <owner>/<repoName> # defaults to current repo
        keep_latest: 4
        #delete_tag_pattern: beta # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: 'Delete Artifact'
      shell: pwsh
      run: |
         cd src
         cd DirBrowser
         cd DirBrowser7
         #Remove-Item -Recurse -Force myappArtifact 


    - name: dotnet publish for azure
      run: |
       cd src
       cd DirBrowser
       cd DirBrowser7
       dotnet publish -c Release -o myapp 
       dir myapp 
  # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
       app-name: ${{ env.AZURE_WEBAPP_NAME }} 
       publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB8E17038FCC4CF1BB35DBFDD06C1AA3  }} 
       package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

